# Generated by Django 2.2.15 on 2022-07-31 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomChatMessages',
            new_name='RoomChatMessage',
        ),
        migrations.AlterModelManagers(
            name='roomchatmessage',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
